// apps/poc-vue-vite/src/components/ui/Card.vue
<template>
  <div
    data-slot="card"
    class="bg-card text-card-foreground flex flex-col gap-6 rounded-xl border px-4 py-3"
    :class="className"
  >
    <div
      v-if="$slots.header"
      data-slot="card-header"
      class="flex flex-col gap-2"
    >
      <slot name="header"></slot>
    </div>
    <div v-if="$slots.title" data-slot="card-title">
      <slot name="title"></slot>
    </div>
    <div v-if="$slots.body" data-slot="card-body" class="flex flex-col gap-4">
      <slot name="body"></slot>
    </div>
    <slot></slot>
    <div
      v-if="$slots.footer"
      data-slot="card-footer"
      class="mt-6 flex justify-end gap-2"
    >
      <slot name="footer"></slot>
    </div>
  </div>
</template>

<script setup lang="ts">
defineProps<{
  className?: string;
}>();
</script>

// apps/poc-react-vite/src/components/ui/card.tsx
import * as React from "react";

import { cn } from "./utils";

function Card({ className, ...props }: React.ComponentProps<"div">) {
  return (
    <div
      data-slot="card"
      className={cn(
        "bg-card text-card-foreground flex flex-col gap-6 rounded-xl border",
        className,
      )}
      {...props}
    />
  );
}

function CardHeader({ className, ...props }: React.ComponentProps<"div">) {
  return (
    <div
      data-slot="card-header"
      className={cn(
        "@container/card-header grid auto-rows-min grid-rows-[auto_auto] items-start gap-1.5 px-6 pt-6 has-data-[slot=card-action]:grid-cols-[1fr_auto] [.border-b]:pb-6",
        className,
      )}
      {...props}
    />
  );
}

function CardTitle({ className, ...props }: React.ComponentProps<"div">) {
  return (
    <h4
      data-slot="card-title"
      className={cn("leading-none", className)}
      {...props}
    />
  );
}

function CardDescription({ className, ...props }: React.ComponentProps<"div">) {
  return (
    <p
      data-slot="card-description"
      className={cn("text-muted-foreground", className)}
      {...props}
    />
  );
}

function CardImage({ className, alt, ...props }: React.ComponentProps<"img">) {
  return (
    <img
      data-slot="card-image"
      alt={alt}
      className={cn("w-full rounded-t-xl object-cover", className)}
      {...props}
    />
  );
}

function CardAction({ className, ...props }: React.ComponentProps<"div">) {
  return (
    <div
      data-slot="card-action"
      className={cn(
        "col-start-2 row-span-2 row-start-1 self-start justify-self-end",
        className,
      )}
      {...props}
    />
  );
}

function CardContent({ className, ...props }: React.ComponentProps<"div">) {
  return (
    <div
      data-slot="card-content"
      className={cn("px-6", className)}
      {...props}
    />
  );
}

function CardFooter({ className, ...props }: React.ComponentProps<"div">) {
  return (
    <div
      data-slot="card-footer"
      className={cn("flex items-center px-6 pb-6 [.border-t]:pt-6", className)}
      {...props}
    />
  );
}

// Compound component — slots pattern (dot-notation)
const CardCompound = Object.assign(Card, {
  Header: CardHeader,
  Content: CardContent,
  Body: CardContent,
  Footer: CardFooter,
  Title: CardTitle,
  Description: CardDescription,
  Action: CardAction,
  Image: CardImage,
});

export {
  CardCompound as Card,
  CardHeader,
  CardFooter,
  CardTitle,
  CardAction,
  CardDescription,
  CardImage,
  CardContent,
};
